### ISSUE TITLE
Support custom Worldguard flags

### ISSUE THREAD

**Issue by knightzmc** [knightzmc/PrivateMines#29]
PrivateMines should should have a section in its config to set default worldguard flags, for both the mine region and the entire region

Proposed config format
```yaml
Flags:
    Mine: 
       - block-break allow
      ﻿ - teleport deny
    Main:
       - block-break deny
       - mob-spawn deny
```
